### ISSUE TITLE
TypeError: A nonempty items array is required

### ISSUE THREAD

**Issue by aditiapratama** [Allar/ue4-mp-downloader#5]
Hello, I've got the following error when running your script 

```node
/home/aditia/.nvm/versions/node/v8.7.0/lib/node_modules/ue4-mp-downloader/node_modules/console-menu/console-menu.js:23
        throw new TypeError('A nonempty items array is required.');
        ^

TypeError: A nonempty items array is required.
    at menu (/home/aditia/.nvm/versions/node/v8.7.0/lib/node_modules/ue4-mp-downloader/node_modules/console-menu/console-menu.js:23:15)
    at ShowDownloadAssetsMenu (/home/aditia/.nvm/versions/node/v8.7.0/lib/node_modules/ue4-mp-downloader/downloader.js:116:2)
    at MenuLoop (/home/aditia/.nvm/versions/node/v8.7.0/lib/node_modules/ue4-mp-downloader/downloader.js:102:5)
    at OnLogin.epic_api.GetOwnedAssets (/home/aditia/.nvm/versions/node/v8.7.0/lib/node_modules/ue4-mp-downloader/downloader.js:105:6)
    at global.epic_api.GetConsolidatedAssetInfo (/home/aditia/.nvm/versions/node/v8.7.0/lib/node_modules/ue4-mp-downloader/epic_api.js:421:9)
    at Request._callback (/home/aditia/.nvm/versions/node/v8.7.0/lib/node_modules/ue4-mp-downloader/epic_api.js:467:5)
    at Request.self.callback (/home/aditia/.nvm/versions/node/v8.7.0/lib/node_modules/ue4-mp-downloader/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/aditia/.nvm/versions/node/v8.7.0/lib/node_modules/ue4-mp-downloader/node_modules/request/request.js:1163:10)
```

**Comment by jeremyfix** [comment]
I've got exactly the same issue.

**Comment by tlind** [comment]
Same here.

**Comment by Allar** [comment]
Holy fuck I didn't get a notification about this. Also I have no idea what this is, hmmm..

**Comment by tonyszhang** [comment]
Same issue. 16.04LTS
Thanks

**Comment by uzername123** [comment]
same Centos7.2
rh-nodejs8

**Comment by adrianmarino** [comment]
same Archlinux
node v6.13.1  and v9.2.0.

**Comment by Yhozen** [comment]
Same here
Ubuntu 17.04
node v6.12.2
